### PR TITLE
fix dark solarized color

### PR DESCRIPTION
**Pull request by wdjunaidi**
Update the solarized color definition to match those in http://ethanschoonover.com/solarized/vim-colors-solarized#the-values

### CODE REVIEW

**Comment by joonro** [comment]
Hi - thanks for the pull request. 

However, it would have been better had you included more explanations, because I actually do not see how your changes match the original ones better. In PowerShell, if you do:

``` posh
> [enum]::GetValues([System.ConsoleColor]) | Foreach-Object {Write-Host $_ -ForegroundColor $_}      
```

(for example, http://blogs.technet.com/b/gary/archive/2013/11/21/sample-all-powershell-console-colors.aspx)

It will print out the syntax-highlighted color names, and you will see my color settings match the colors pretty well. (I should fix the color code for `White` it seems.)

Also if I apply your changes, the PowerShell console does not look like the screenshots in the http://ethanschoonover.com/solarized at all (mine does) - it looks pretty ugly.

I tested these schemes only with PowerShell - (since I do not use others) and I wonder 
the "correct scheme" is different for different terminal program you use (cmd, git bash, PowerShell, etc).  
Could you please explain why you think your changes match the original color better?

**Comment by wdjunaidi** [comment]
Hi,

My fault, I didn't see that your theme is for PowerShell only. I'm using ConsoleZ with regular cmd.exe and git-bash, I guess that was why when I import your theme it didn't look like solarized version. 

I guess you can just ignore this pull-request then.

**Comment by joonro** [comment]
I see - thanks for letting me know. Maybe it is better to have color themes for different applications available. It is weird that different colors are applied for different applications. I actually started using ConEmu these days and it uses consistent color across different shells.

**Comment by joonro** [comment]
Hi,

I was confused because I forgot to set the correct background color which needs to be set separately. Now once I set that, the Git Bash shell in ConsoleZ with my color scheme looks good. So it is not about PowerShell.

Here is the screenshot of mine:

image

The screenshot with your color:

image

Your scheme looks okay too, but I think mine is closer to the original. Please let me know what you think.

**Comment by wdjunaidi** [comment]
I think that looks good. Glad that you find the problem. I should try with my local background also.

**Comment by joonro** [comment]
Good! Please let me know if you want to keep your color scheme, I can easily maintain it under different file name as a different version of solarized.

**Comment by wdjunaidi** [comment]
Nah, not necessary. Just ignore it

**Comment by joonro** [comment]
I see. I added a note on the background color in the `README`. Thank you.

**Pull request closed without merging**
